apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msa-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/onetouch-ke/multi-Devops.git
    targetRevision: HEAD
    path: mychart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
