frontend:
  image: 013958955750.dkr.ecr.ap-northeast-2.amazonaws.com/multi-frontend
  tag: 38
  port: 80

backend:
  image: 013958955750.dkr.ecr.ap-northeast-2.amazonaws.com/multi-backend
  tag: 37
  port: 8080

ingress:
  enabled: true
  host: ""  #ALB가 생성하는 DNS 주소
