apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.mariadb.image }}:{{ .Values.mariadb.tag }}"
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "{{ .Values.mariadb.rootPassword }}"
        ports:
        - containerPort: {{ .Values.mariadb.port }}
      imagePullSecrets:
      - name: ecr-secret